package com.e1858.common;

import java.text.Collator;
import java.text.SimpleDateFormat;

public class Constant
{
	public final static String				PRODUCTNAME								= "高校通";
	public final static String				BASE_URL								= "http://218.28.143.93:8200/httpapi.aspx";
	public final static String				USER_INFO								= "UserInfo";
	public final static String				USERNAME								= "username";
	public final static String				PASSWORD								= "password";
	public final static String				IS_PWD									= "ispwd";
	public final static String				IS_AUTO_LOGIN							= "isAutologin";
	public final static int					SOCKET_RECONNECT_INTERVAL				= 5 * 1000;
	public static int						SOCKET_ACTIVETEST_INTERVAL				= 90 * 1000;
	public final static int					CONNECT_TIMEOUT							= 60 * 1000;
	public final static int					NETWORK_CHECK_INTERVAL					= 5 * 1000;
	public final static int					NETWORK_AVAILABLE_SOCKET_OPEN_INTERVAL	= 5000;
	public final static int					LOCATION_LISTEN_INTERVAL				= 60 * 1000;
	
	public final static String              VERSION_KEY                             ="VersionKey";
	public final static String				TAG_APP									= "app";
	public final static String				TAG_ACTIVITY_LIFE						= "activityLife";
	public final static String				TAG_NETWORK								= "network";
	public final static String				TAG_NETWORK_SOCKET						= "network_socket";
	public final static String				TAG_NETWORK_UDP							= "network_UDP";
	public final static String				TAG_NETWORK_HTTP						= "network_http";
	public final static String				TAG_BROADCAST_RECEIVER					= "broadcastReceiver";
	public final static String				TAG_CALL								= "call";
	public final static String				TAG_SMS									= "sms";
	public final static String				TAG_ENCRYPT								= "encrypt";
	public final static String				TAG_PROTOCOL							= "protocol";
	public final static String				TAG_PROTOCOL_SOCKET						= "protocolSocket";
	public final static String				TAG_PROTOCOL_HTTP						= "protocolHTTP";
	public final static String				TAG_PROTOCOL_ANALYZE					= "protocolAnalyze";
	public final static String				TAG_UTILS_FILE							= "utils_File";
	public final static String				TAG_ASYNC_IMAGE_LOADER					= "async_image_loader";
	public final static String				TAG_LOCATION							= "LocationUtil";
	public final static String				TAG_CEAPP								= "CEApp";

	public final static String				LUA_COMMENT								= "--";
	public final static String				ENCODING								= "UTF-8";
	public final static String				PATH_SEPARATOR							= System.getProperty("path.separator");
	public final static String				FILE_SEPARATOR							= System.getProperty("file.separator");
	public final static String				LINE_SEPARATOR							= System.getProperty("line.separator");

	public final static String				CR_LF									= "\r\n";
	public final static String				TWO_HYPHEN								= "--";
	public final static String				BOUNDARY								= "--boundary=_NextPart_000_00EE_01C07425.958FDFE0";
	public final static String				DES3_KEY								= "www.e1858.com";
	
	public static final String				PICTURE_EXTENSION						= ".png";
	public static final String				IMAGE_TYPE								= "image/*";

	public final static double				MAX_LATITUDE							= 360;
	public final static double				MAX_LONGITUDE							= 360;

	public final static float[]				COLOR_SELECTED							= new float[] { 0.308f, 0.609f, 0.082f, 0, 0, 0.308f, 0.609f, 0.082f, 0, 0, 0.308f, 0.609f, 0.082f, 0, 0, 0, 0, 0, 1, 0 };

	public final static int					ONE_KB									= 1024;
	public final static int					ONE_MB									= ONE_KB * 1024;
	public final static int					CACHE_SIZE								= 5 * ONE_MB;
	public final static int					FREE_SD_SPACE_NEEDED_TO_CACHE			= CACHE_SIZE;
	public final static String				CACHDIR									= "data/ceapp/cache/imgcache";
	public final static String				APKNAME									= "CEapp.apk";
	public final static String				WHOLESALE_CONV							= ".cach";
	public final static int					REMOVE_CACHE_PERCENT					= 40;
	public final static SimpleDateFormat	SIMPLE_DATE_FORMAT						= new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
	public final static SimpleDateFormat	SIMPLE_DATE_FORMAT_LONG					= new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSSS");
	public final static SimpleDateFormat    SIMPLE_DATE_FORMAT_NEW                  = new SimpleDateFormat("yyyyMMddHHmmss");

	public final static Collator			COLLATOR								= Collator.getInstance(java.util.Locale.CHINA);

	
	
	public final static String PATH="data/ceapp/cache/file/";
	public final static String[][] MIME_MapTable={
		    //{后缀名，    MIME类型}
		{"3gp","video/3gpp"},
		{"aab","application/x-authoware-bin"},
		{"aam","application/x-authoware-map"},
		{"aas","application/x-authoware-seg"},
		{"ai","application/postscript"},
		{"aiff","audio/x-aiff"},
		{"als","audio/X-Alpha5"},
		{"amc","application/x-mpeg"},
		{"apk","application/vnd.android.package-archive"},
		{"asf","video/x-ms-asf"},
		{"asn","application/astound"},
		{"asp","application/x-asap"},
		{"asx","video/x-ms-asf"},
		{"au","audio/basic"},
		{"avi","video/x-msvideo"},
		{"awb","audio/amr-wb"},
		{"bcpio","application/x-bcpio"},
		{"bld","application/bld"},
		{"bld2","application/bld2"},
		{"bmp","image/bmp"},
		{"bz2","application/x-bzip2"},
		{"cal","image/x-cals"},
		{"ccn","application/x-cnc"},
		{"cco","application/x-cocoa"},
		{"cdf","application/x-netcdf"},
		{"cgi","magnus-internal/cgi"},
		{"chat","application/x-chat"},
		{"clp","application/x-msclip"},
		{"cmx","application/x-cmx"},
		{"co","application/x-cult3d-object"},
		{"cod","image/cis-cod"},
		{"cpio","application/x-cpio"},
		{"cpt","application/mac-compactpro"},
		{"crd","application/x-mscardfile"},
		{"csh","application/x-csh"},
		{"csml","chemical/x-csml"},
		{"css","text/css"},
		{"dcr","application/x-director"},
		{"dcx","image/x-dcx"},
		{"dir","application/x-director"},
		{"doc","application/msword"},
		{"dot","application/x-dot"},
		{"dvi","application/x-dvi"},
		{"dwf","drawing/x-dwf"},
		{"dxf","application/x-autocad"},
		{"dxr","application/x-director"},
		{"ebk","application/x-expandedbook"},
		{"embl","chemical/x-embl-dl-nucleotide"},
		{"eps","application/postscript"},
		{"eri","image/x-eri"},
		{"esl","audio/echospeech"},
		{"etc","application/x-earthtime"},
		{"etx","text/x-setext"},
		{"evm","x-lml/x-evm"},
		{"evy","application/x-envoy"},
		{"fhc","image/x-freehand"},
		{"fif","image/fif"},
		{"fm","application/x-maker"},
		{"fpx","image/x-fpx"},
		{"fvi","video/isivideo"},
		{"gau","chemical/x-gaussian-input"},
		{"gca","application/x-gca-compressed"},
		{"gdb","x-lml/x-gdb"},
		{"gif","image/gif"},
		{"gps","application/x-gps"},
		{"gtar","application/x-gtar"},
		{"gz","application/x-gzip"},
		{"hdf","application/x-hdf"},
		{"hdml","text/x-hdml"},
		{"hlp","application/winhlp"},
		{"hqx","application/mac-binhex40"},
		{"html","text/html"},
		{"ice","x-conference/x-cooltalk"},
		{"ief","image/ief"},
		{"ifs","image/ifs"},
		{"imy","audio/melody"},
		{"ins","application/x-NET-Install"},
		{"ips","application/x-ipscript"},
		{"ipx","application/x-ipix"},
		{"itz","audio/x-mod"},
		{"ivr","i-world/i-vrml"},
		{"j2k","image/j2k"},
		{"jad","text/vnd.sun.j2me.app-descriptor"},
		{"jam","application/x-jam"},
		{"jar","application/java-archive"},
		{"jnlp","application/x-java-jnlp-file"},
		{"jpg","image/jpeg"},
		{"js","application/x-javascript"},
		{"jwc","application/jwc"},
		{"kjx","application/x-kjx"},
		{"lak","x-lml/x-lak"},
		{"latex","application/x-latex"},
		{"lcc","application/fastman"},
		{"lcr","application/x-digitalloca"},
		{"lgh","application/lgh"},
		{"lml","x-lml/x-lml"},
		{"lmlpack","x-lml/x-lmlpack"},
		{"lsx","video/x-ms-asf"},
		{"lzh","application/x-lzh"},
		{"m14","application/x-msmediaview"},
		{"m15","audio/x-mod"},
		{"m3u","audio/x-mpegurl"},
		{"m3url","audio/x-mpegurl"},
		{"ma1","audio/ma1"},
		{"ma2","audio/ma2"},
		{"ma3","audio/ma3"},
		{"ma5","audio/ma5"},
		{"man","application/x-troff-man"},
		{"map","magnus-internal/imagemap"},
		{"mbd","application/mbedlet"},
		{"mct","application/x-mascot"},
		{"mdb","application/x-msaccess"},
		{"mdz","audio/x-mod"},
		{"me","application/x-troff-me"},
		{"mel","text/x-vmel"},
		{"midi","audio/midi"},
		{"mif","application/x-mif"},
		{"mil","image/x-cals"},
		{"mio","audio/x-mio"},
		{"mmf","application/x-skt-lbs"},
		{"mng","video/x-mng"},
		{"mny","application/x-msmoney"},
		{"mocha","application/x-mocha"},
		{"mod","audio/x-mod"},
		{"mof","application/x-yumekara"},
		{"mol","chemical/x-mdl-molfile"},
		{"mop","chemical/x-mopac-input"},
		{"mov","video/quicktime"},
		{"movie","video/x-sgi-movie"},
		{"mp3","audio/x-mpeg"},
		{"mp4","video/mp4"},
		{"mpc","application/vnd.mpohun.certificate"},
		{"mpeg","video/mpeg"},
		{"mpg4","video/mp4"},
		{"mpn","application/vnd.mophun.application"},
		{"mpp","application/vnd.ms-project"},
		{"mps","application/x-mapserver"},
		{"mrl","text/x-mrml"},
		{"mrm","application/x-mrm"},
		{"ms","application/x-troff-ms"},
		{"mts","application/metastream"},
		{"nar","application/zip"},
		{"nbmp","image/nbmp"},
		{"nc","application/x-netcdf"},
		{"ndb","x-lml/x-ndb"},
		{"ndwn","application/ndwn"},
		{"nif","application/x-nif"},
		{"nmz","application/x-scream"},
		{"nokia-op-logo","image/vnd.nok-oplogo-color"},
		{"npx","application/x-netfpx"},
		{"nsnd","audio/nsnd"},
		{"nva","application/x-neva1"},
		{"oda","application/oda"},
		{"oom","application/x-AtlasMate-Plugin"},
		{"pac","audio/x-pac"},
		{"ae","audio/x-epac"},
		{"pan","application/x-pan"},
		{"pbm","image/x-portable-bitmap"},
		{"pcx","image/x-pcx"},
		{"pda","image/x-pda"},
		{"pdb","chemical/x-pdb"},
		{"pdf","application/pdf"},
		{"pfr","application/font-tdpfr"},
		{"pgm","image/x-portable-graymap"},
		{"pict","image/x-pict"},
		{"pm","application/x-perl"},
		{"pmd","application/x-pmd"},
		{"png","image/png"},
		{"pnm","image/x-portable-anymap"},
		{"pnz","image/png"},
		{"pot","application/vnd.ms-powerpoint"},
		{"ppm","image/x-portable-pixmap"},
		{"pps","application/vnd.ms-powerpoint"},
		{"ppt","application/vnd.ms-powerpoint"},
		{"pqf","application/x-cprplayer"},
		{"pqi","application/cprplayer"},
		{"prc","application/x-prc"},
		{"proxy","application/x-ns-proxy-autoconfig"},
		{"ps","application/postscript"},
		{"ptlk","application/listenup"},
		{"pub","application/x-mspublisher"},
		{"pvx","video/x-pv-pvx"},
		{"qcp","audio/vnd.qcelp"},
		{"qt","video/quicktime"},
		{"qti","image/x-quicktime"},
		{"qtif","image/x-quicktime"},
		{"r3t","text/vnd.rn-realtext3d"},
		{"ra","audio/x-pn-realaudio"},
		{"ram","audio/x-pn-realaudio"},
		{"rar","application/x-rar-compressed"},
		{"ras","image/x-cmu-raster"},
		{"rdf","application/rdf+xml"},
		{"rf","image/vnd.rn-realflash"},
		{"rgb","image/x-rgb"},
		{"rlf","application/x-richlink"},
		{"rm","audio/x-pn-realaudio"},
		{"rmf","audio/x-rmf"},
		{"rmm","audio/x-pn-realaudio"},
		{"rmvb","audio/x-pn-realaudio"},
		{"rnx","application/vnd.rn-realplayer"},
		{"roff","application/x-troff"},
		{"rp","image/vnd.rn-realpix"},
		{"rpm","audio/x-pn-realaudio-plugin"},
		{"rt","text/vnd.rn-realtext"},
		{"rte","x-lml/x-gps"},
		{"rtf","application/rtf"},
		{"rtg","application/metastream"},
		{"rtx","text/richtext"},
		{"rv","video/vnd.rn-realvideo"},
		{"rwc","application/x-rogerwilco"},
		{"s3m","audio/x-mod"},
		{"s3z","audio/x-mod"},
		{"sca","application/x-supercard"},
		{"scd","application/x-msschedule"},
		{"sdf","application/e-score"},
		{"sea","application/x-stuffit"},
		{"sgm","text/x-sgml"},
		{"sgml","text/x-sgml"},
		{"sh","application/x-sh"},
		{"shar","application/x-shar"},
		{"shtml","magnus-internal/parsed-html"},
		{"shw","application/presentations"},
		{"si6","image/si6"},
		{"si7","image/vnd.stiwap.sis"},
		{"si9","image/vnd.lgtwap.sis"},
		{"sis","application/vnd.symbian.install"},
		{"sit","application/x-stuffit"},
		{"skd","application/x-Koan"},
		{"skm","application/x-Koan"},
		{"skp","application/x-Koan"},
		{"skt","application/x-Koan"},
		{"slc","application/x-salsa"},
		{"smd","audio/x-smd"},
		{"smi","application/smil"},
		{"smil","application/smil"},
		{"smp","application/studiom"},
		{"smz","audio/x-smd"},
		{"snd","audio/basic"},
		{"spc","text/x-speech"},
		{"spl","application/futuresplash"},
		{"spr","application/x-sprite"},
		{"sprite","application/x-sprite"},
		{"spt","application/x-spt"},
		{"src","application/x-wais-source"},
		{"stk","application/hyperstudio"},
		{"stm","audio/x-mod"},
		{"sv4cpio","application/x-sv4cpio"},
		{"sv4crc","application/x-sv4crc"},
		{"svf","image/vnd"},
		{"svg","image/svg-xml"},
		{"svh","image/svh"},
		{"svr","x-world/x-svr"},
		{"swf","application/x-shockwave-flash"},
		{"swfl","application/x-shockwave-flash"},
		{"t","application/x-troff"},
		{"talk","text/x-speech"},
		{"tar","application/x-tar"},
		{"taz","application/x-tar"},
		{"tbp","application/x-timbuktu"},
		{"tbt","application/x-timbuktu"},
		{"tcl","application/x-tcl"},
		{"tex","application/x-tex"},
		{"texi","application/x-texinfo"},
		{"texinfo","application/x-texinfo"},
		{"tgz","application/x-tar"},
		{"thm","application/vnd.eri.thm"},
		{"tif","image/tiff"},
		{"tiff","image/tiff"},
		{"tki","application/x-tkined"},
		{"tkined","application/x-tkined"},
		{"toc","application/toc"},
		{"toy","image/toy"},
		{"tr","application/x-troff"},
		{"trk","x-lml/x-gps"},
		{"trm","application/x-msterminal"},
		{"tsi","audio/tsplayer"},
		{"tsp","application/dsptype"},
		{"tsv","text/tab-separated-values"},
		{"ttf","application/octet-stream"},
		{"ttz","application/t-time"},
		{"txt","text/plain"},
		{"ult","audio/x-mod"},
		{"ustar","application/x-ustar"},
		{"uu","application/x-uuencode"},
		{"uue","application/x-uuencode"},
		{"vcd","application/x-cdlink"},
		{"vcf","text/x-vcard"},
		{"vdo","video/vdo"},
		{"vib","audio/vib"},
		{"viv","video/vivo"},
		{"vivo","video/vivo"},
		{"vmd","application/vocaltec-media-desc"},
		{"vmf","application/vocaltec-media-file"},
		{"vmi","application/x-dreamcast-vms-info"},
		{"vms","application/x-dreamcast-vms"},
		{"vox","audio/voxware"},
		{"vqe","audio/x-twinvq-plugin"},
		{"vqf","audio/x-twinvq"},
		{"vql","audio/x-twinvq"},
		{"vre","x-world/x-vream"},
		{"vrml","x-world/x-vrml"},
		{"vrt","x-world/x-vrt"},
		{"vrw","x-world/x-vream"},
		{"vts","workbook/formulaone"},
		{"wav","audio/x-wav"},
		{"wax","audio/x-ms-wax"},
		{"wbmp","image/vnd.wap.wbmp"},
		{"web","application/vnd.xara"},
		{"wi","image/wavelet"},
		{"wis","application/x-InstallShield"},
		{"wm","video/x-ms-wm"},
		{"wma","audio/x-ms-wma"},
		{"wmd","application/x-ms-wmd"},
		{"wmf","application/x-msmetafile"},
		{"wml","text/vnd.wap.wml"},
		{"wmlc","application/vnd.wap.wmlc"},
		{"wmls","text/vnd.wap.wmlscript"},
		{"wmlsc","application/vnd.wap.wmlscriptc"},
		{"wmlscript","text/vnd.wap.wmlscript"},
		{"wmv","audio/x-ms-wmv"},
		{"wmx","video/x-ms-wmx"},
		{"wmz","application/x-ms-wmz"},
		{"wpng","image/x-up-wpng"},
		{"wpt","x-lml/x-gps"},
		{"wri","application/x-mswrite"},
		{"wrz","x-world/x-vrml"},
		{"ws","text/vnd.wap.wmlscript"},
		{"wsc","application/vnd.wap.wmlscriptc"},
		{"wv","video/wavelet"},
		{"wvx","video/x-ms-wvx"},
		{"wxl","application/x-wxl"},
		{"x-gzip","application/x-gzip"},
		{"xar","application/vnd.xara"},
		{"xbm","image/x-xbitmap"},
		{"xdma","application/x-xdma"},
		{"xdw","application/vnd.fujixerox.docuworks"},
		{"xhtml","application/xhtml+xml"},
		{"xlc","application/vnd.ms-excel"},
		{"xll","application/x-excel"},
		{"xls","application/vnd.ms-excel"},
		{"xml","text/xml"},
		{"xmz","audio/x-mod"},
		{"xpi","application/x-xpinstall"},
		{"xpm","image/x-xpixmap"},
		{"xul","text/xul"},
		{"xwd","image/x-xwindowdump"},
		{"xyz","chemical/x-pdb"},
		{"yz1","application/x-yz1"},
		{"z","application/x-compress"},
		{"zac","application/x-zaurus-zac"},
		{"zip","application/zip"}
		};
	
}
